### ISSUE TITLE
Why is this fork

### ISSUE THREAD

**Issue by sngo25** [linagora/node-ldapauth-fork#1]
This is a serious issue in the library, uncaught error will happen when LDAP server is down, there is a PR but the author is not going to merge it: https://github.com/vesse/node-ldapauth-fork/pull/41

**Comment by dbenchi** [comment]
https://github.com/vesse/node-ldapauth-fork/pull/41#issuecomment-265963284

**Comment by sngo25** [comment]
The PR is merged.
